TILE_SIZE = 16
MAP_WIDTH, MAP_HEIGHT = 25, 15
WIDTH = TILE_SIZE * MAP_WIDTH
WHITE = (255, 255, 255)
FPS = 30
HEADER_HEIGHT = 50  # Высота верхней части для таймера и счета
HEIGHT = TILE_SIZE * MAP_HEIGHT + HEADER_HEIGHT